# Generated by Django 5.2 on 2025-05-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_type', models.CharField(choices=[('PLAYER_PERFORMANCE', 'Player Performance Prediction'), ('MATCH_OUTCOME', 'Match Outcome Prediction'), ('PLAYER_COMPARISON', 'Player Comparison'), ('TEAM_PERFORMANCE', 'Team Performance Prediction')], max_length=50)),
                ('description', models.TextField()),
                ('file_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_type'], name='ml_models_m_model_t_46c46f_idx'), models.Index(fields=['is_active'], name='ml_models_m_is_acti_afbf29_idx'), models.Index(fields=['version'], name='ml_models_m_version_becebc_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('importance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ml_models.mlmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['model'], name='ml_models_m_model_i_706764_idx'), models.Index(fields=['name'], name='ml_models_m_name_e3d76b_idx')],
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('PLAYER_STATS', 'Player Statistics'), ('MATCH_WINNER', 'Match Winner'), ('SCORE', 'Score Prediction'), ('PLAYER_COMPARISON', 'Player Comparison')], max_length=50)),
                ('prediction_data', models.JSONField()),
                ('confidence', models.FloatField()),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stats.match')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.mlmodel')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stats.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stats.team')),
            ],
            options={
                'indexes': [models.Index(fields=['prediction_type'], name='ml_models_p_predict_3658af_idx'), models.Index(fields=['match'], name='ml_models_p_match_i_c0b3e2_idx'), models.Index(fields=['player'], name='ml_models_p_player__506188_idx'), models.Index(fields=['team'], name='ml_models_p_team_id_13e4f1_idx'), models.Index(fields=['created_at'], name='ml_models_p_created_5a7427_idx')],
            },
        ),
    ]
